# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:jdk11

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - download
  - convert
  - build
  - start-server
  - load
  - query
  - stop-server
  - report

omlDependencies:
  stage: download
  script: ./gradlew omlDependencies
  artifacts:
    paths:
      - build/

omlToOwl:
  stage: convert
  script: ./gradlew omlToOwl -x omlDependencies
  artifacts:
    paths:
      - build/

owlReason:
  stage: build
  script: ./gradlew owlReason -x omlToOwl
  artifacts:
    paths:
      - build/

startFuseki:
  stage: start-server
  script: ./gradlew startFuseki
  artifacts:
    paths:
      - .fuseki/

owlLoad:
  stage: load
  script: ./gradlew owlLoad -x owlReason
  artifacts:
    paths:
      - build/

owlQuery:
  stage: query
  script: ./gradlew owlQuery -x owlLoad
  artifacts:
    paths:
      - build/

stopFuseki:
  stage: stop-server
  script: ./gradlew stopFuseki
  artifacts:
    paths:
      - .fuseki/

generateWebsite:
  stage: report
  script: ./gradlew generateWebsite
  artifacts:
    paths:
      - build/
