# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:jdk11

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - check
  - analyze
  - report
  - publish

check:
  stage: check
  script: ./gradlew build
  artifacts:
    paths:
      - build/

analyze:
  stage: analyze
  script: ./gradlew startFuseki owlQuery stopFuseki -x owlReason
  artifacts:
    paths:
      - build/

report:
  stage: report
  script: ./gradlew generateWebsite -x owlQuery
  artifacts:
    paths:
      - build/

pages:
  stage: publish
  script:
    - mv build/web public
  artifacts:
    paths:
      - public
  only:
    - main