name: kepler16b-workflow

# Controls when the workflow will run
on:
  # default workflow runs for all branches and tags
  push:
    branches: '**' 
    tags: '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
# Environment Variable
env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  kepler16b-workflow:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java and Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          # https://github.com/actions/setup-java#supported-distributions
          distribution: 'adopt'

      - name: before_script
        run: echo "GRADLE_USER_HOME=$(pwd)/.gradle" >> $GITHUB_ENV

      - name: check
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with: 
          name: check-artifacts
          path: build
      
      - name: analyze
        run: ./gradlew startFuseki owlQuery stopFuseki -x owlReason

      - uses: actions/upload-artifact@v2
        with: 
          name: analyze-artifacts
          path: build

      - name: report
        run: ./gradlew generateWebsite -x owlQuery

      - uses: actions/upload-artifact@v2
        with: 
          name: report-artifacts
          path: build

      - name: pages [MAIN]
        run: mv build/web public
        if: ${{ github.ref_name == 'main' }} # Run job on main branch only

      - uses: actions/upload-artifact@v2 [MAIN]
        with: 
          name: pages-artifacts
          path: public
        if: ${{ github.ref_name == 'main' }} # Run job on main branch only