name: kepler16b-workflow

# Controls when the workflow will run
on:
  # default workflow runs for all branches and tags
  push:
    branches: ['**'] 
    tags: ['**']
  # Write access is needed to publish to Github Pages
permissions:
  contents: write

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
# Environment Variable
env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  kepler16b-workflow:
    runs-on: ubuntu-latest
    container: gradle:jdk11
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      # @v3 = Major version 3
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java and Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          # https://github.com/actions/setup-java#supported-distributions
          distribution: 'adopt'

      - name: before_script
        run: echo "GRADLE_USER_HOME=$(pwd)/.gradle" >> $GITHUB_ENV

      - name: check
        run: ./gradlew build

      - name: Upload Check Artifacts 
        uses: actions/upload-artifact@v3
        with: 
          name: check-artifacts
          path: build
      
      - name: analyze
        run: ./gradlew startFuseki owlQuery stopFuseki -x owlReason

      - name: Upload Analyze Artifacts 
        uses: actions/upload-artifact@v3
        with: 
          name: analyze-artifacts
          path: build

      - name: report
        run: ./gradlew generateWebsite -x owlQuery

      - name: Upload Report Artifacts 
        uses: actions/upload-artifact@v3
        with: 
          name: report-artifacts
          path: build

      - name: pages [MAIN]
        run: mv build/web public
        if: ${{ github.ref_name == 'main' }} # Run job on main branch only

      - name: Upload Pages Artifacts [MAIN]
        uses: actions/upload-artifact@v3
        with: 
          name: pages-artifacts
          path: public
        if: ${{ github.ref_name == 'main' }} # Run job on main branch only

      - name: Install rsync to Gradle Image [MAIN]
        run: apt-get update && apt-get -y install rsync
        if: ${{ github.ref_name == 'main' }} # Run job on main branch only

      - name: Deploy to Github Pages [MAIN]
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
        if: ${{ github.ref_name == 'main' }} # Run job on main branch only